baseURL: https://wetrust.netlify.app
title: WETRUST
theme: omega-hugo
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - name: Home
      pre: ''
      url: /
      weight: 1
    - name: About
      pre: '#'
      url: mission
      weight: 2
    - name: Products
      pre: '#'
      url: products
      weight: 3
    - name: Career
      pre: ''
      url: career
      weight: 4
    - name: Contact
      pre: '#'
      url: contact
      weight: 5
params:
  author: Themefisher
  contact_info:  Plot No. 16 Street No. 16<br>Ranaji Enclave Near Chetna Model Public School, <br>Najafgarh, ND-110043
  cookies:
    enable: yes
    expire_days: 2
  description: wetrust iso 9001-2015
  logo: images/logo.png
  logo_width: 120px
  map:
    enable: No
    gmap_api: https://maps.googleapis.com/maps/api/js?key=*****
    map_center_lat: '28.50000'
    map_center_lng: '77.16000'
    map_marker: images/map-marker.png
    map_position_lat: '28.592'
    map_position_lng: '77.162'
  preloader: yes
  social:
    - icon: fa-facebook
      link: '#'
      title: facebook
    - icon: fa-twitter
      link: '#'
      title: twitter
    - icon: fa-instagram
      link: '#'
      title: instagram
    - icon: fa-github
      link: '#'
      title: github
    - icon: fa-linkedin
      link: '#'
      title: linkedin
